# testing properties

server:
  port: 8082
grpc:
  server:
    port: 9092

# application properties

spring:
  application:
    name: problem-management

    # database properties
  security:
    oauth2:
      client:
        provider:
          cm-pse-22:
            authorization-uri: https://cm-keycloak.cloud.iai.kit.edu/realms/CM/protocol/openid-connect/auth
            token-uri: https://cm-keycloak.cloud.iai.kit.edu/realms/CM/protocol/openid-connect/token
            user-info-uri: https://cm-keycloak.cloud.iai.kit.edu/realms/CM/protocol/openid-connect/userinfo
            jwk-set-uri: https://cm-keycloak.cloud.iai.kit.edu/realms/CM/protocol/openid-connect/certs
            issuer-uri: https://cm-keycloak.cloud.iai.kit.edu/realms/CM

problem:
  baseUrl: http://localhost:8082
  listProblemsUrl: /problems
  createProblemUrl: /problems
  getProblemUrl: /problems/{pin}
  updateProblemUrl: /problems
  removeProblemUrl: /problems/{pin}

# Domain Microservice Building URLs

building:
  baseUrl: http://localhost:8081
  createNotificationUrl: /notifications
  updateNotificationUrl: /notifications
  removeNotificationUrl: /notifications/{nin}

# role authorities
role:
  admin: TM-CM-MULESOFT
  user: TM-CM-JUNIORSTUDENTS